### ISSUE TITLE
Replicate jit-engine CI here

### ISSUE THREAD

**Issue by alexbaden** [intel-ai/hdk#105]
In preparation for repo merge, we should add the GitHub actions from the other repo here, to run under the `omniscidb` folder. We will need to copy the actions over and update the paths.

**Comment by leshikus** [comment]
I continue resolving test linking problems. The current problem is the following.
```
CodeGeneratorTest.cpp:(.text._ZN34CodeGeneratorTest_IntegerExpr_Test8TestBodyEv+0x569): undefined reference to `compiler::verify_function_ir(llvm::Function const*)'
/localdisk2/afedotov/miniconda3/envs/omnisci-dev/bin/../lib/gcc/x86_64-conda-linux-gnu/9.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: CodeGeneratorTest.cpp:(.text._ZN34CodeGeneratorTest_IntegerExpr_Test8TestBodyEv+0x62e): undefined reference to `ScalarCodeGenerator::generateNativeCode(Executor*, ScalarCodeGenerator::CompiledExpression const&, CompilationOptions const&)'
```

I've added `${llvm_libs}` and get less errors in this test, yet something else should be added as well.

**Comment by pbchekin** [comment]
Per our discussion with @alexbaden, we can skip the action "docs"

**Comment by leshikus** [comment]
Should be fixed with https://github.com/intel-ai/hdk/pull/106
