### ISSUE TITLE
Allow building the engine with L0 support in conda environment

### ISSUE THREAD

**Issue by kurapov-peter** [intel-ai/hdk#113]
Since the default L0 driver location is in system libraries, there's an issue when building jit engine. CMake's `find_package` looks for the headers and finds them in `/usr/include`. CMake does not add it to include even if the `target_include_directories` is set explicitly to include the system paths (see https://gitlab.kitware.com/cmake/cmake/-/issues/17966 for details). Providing hints/paths to `find_package` break the linking process for other libraries due to conflicts.
There's also currently no conda package that we could use to avoid using the system includes/libraries. We need to either build a package or create a workaround for building jit-engine with L0 under conda env.

**Comment by leshikus** [comment]
I was trying to install these packages in the github runner and it didn't work. IMO the problem is Intel's public key is for focal, and github already uses jammy.

**Comment by leshikus** [comment]
I've installed packages into the base system and now find_package gives an error ` Could NOT find LevelZero (missing: LevelZero_LIBRARY)`. How did you make it work?

I believe I have the required files in my system: 
```
# find / -name libze*
/usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.1
/usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.1.3.23726.1
/usr/lib/x86_64-linux-gnu/libze_loader.so
/usr/lib/x86_64-linux-gnu/libze_loader.so.1
/usr/lib/x86_64-linux-gnu/libze_loader.so.1.8.1
/usr/lib/x86_64-linux-gnu/libze_tracing_layer.so
/usr/lib/x86_64-linux-gnu/libze_tracing_layer.so.1
/usr/lib/x86_64-linux-gnu/libze_tracing_layer.so.1.8.1
/usr/lib/x86_64-linux-gnu/libze_validation_layer.so
/usr/lib/x86_64-linux-gnu/libze_validation_layer.so.1
/usr/lib/x86_64-linux-gnu/libze_validation_layer.so.1.8.1
/usr/lib/x86_64-linux-gnu/pkgconfig/libze_loader.pc
```

**Comment by kurapov-peter** [comment]
Yes, your installation looks correct. By default, system's cmake looks into those folders and set's up the env correctly (no conda):
```
$ cmake -DENABLE_CUDA=off -DENABLE_L0=on ..
-- LevelZero_LIBRARIES: /usr/lib/x86_64-linux-gnu/libze_loader.sodl
-- LevelZero_INCLUDE_DIRS: /usr/include
...
```

Conda isolates the environment, so if you didn't provide any additional paths it will not find any system library. The ask is exactly that: to find a solution that allows cmake to find the system driver from a conda env.

**Comment by kurapov-peter** [comment]
For conda build I previously had some success specifying the target architecture explicitly via
```
-DCMAKE_LIBRARY_ARCHITECTURE=x86_64-linux-gnu
```
Maybe that can help.

**Comment by leshikus** [comment]
Despite of L0 installation the make reports 

CMake Error at /usr/share/miniconda/envs/omnisci-dev/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LevelZero (missing: LevelZero_INCLUDE_DIR LevelZero_LIBRARY)
https://github.com/intel-ai/hdk/actions/runs/4611746735/jobs/8151817348#step:11:275

**Comment by kurapov-peter** [comment]
Conda L0 build is now part of the CI (#360).
