### ISSUE TITLE
Fix paths for hdk tests

### ISSUE THREAD

**Issue by leshikus** [intel-ai/hdk#120]
Due to path differences the tests do not work for HDK

HDK implementation of `get_root_abs_path` differs because `BUILD_SHARED_LIBS` and `ENABLE_SHARED_LIBS` have different default values for `omniscidb` and `hdk`. This can be fixed with the following patch:

```
diff --git a/OSDependent/Unix/omnisci_path.cpp b/OSDependent/Unix/omnisci_path.cpp
index 0a113fe53..40f98729e 100644
--- a/OSDependent/Unix/omnisci_path.cpp
+++ b/OSDependent/Unix/omnisci_path.cpp
@@ -52,9 +52,10 @@ std::string get_root_abs_path() {
     /* Despite the dlinfo man page claim that l_name is absolute path,
        it is so only when the location path to the library is absolute,
        say, as specified in LD_LIBRARY_PATH. */
+
     std::filesystem::path abs_exe_dir(std::filesystem::absolute(
         std::filesystem::canonical(std::string(link_map->l_name))));
-    const auto mapd_root = abs_exe_dir.parent_path().parent_path();
+    const auto mapd_root = abs_exe_dir.parent_path().parent_path().parent_path();
     return mapd_root.string();
   }
 #endif
```

The next problem is related to Calcite classpath and can be fixed as follows:

```
diff --git a/Calcite/CalciteJNI.cpp b/Calcite/CalciteJNI.cpp
index a98c3787c..c99f5c704 100644
--- a/Calcite/CalciteJNI.cpp
+++ b/Calcite/CalciteJNI.cpp
@@ -119,7 +119,7 @@ class JVM {
   static std::shared_ptr<JVM> createJVM(size_t max_mem_mb) {
     auto root_abs_path = omnisci::get_root_abs_path();
     std::string class_path_arg = "-Djava.class.path=" + root_abs_path +
-                                 "/bin/calcite-1.0-SNAPSHOT-jar-with-dependencies.jar";
+                                 "/../bin/calcite-1.0-SNAPSHOT-jar-with-dependencies.jar";
     std::string max_mem_arg = "-Xmx" + std::to_string(max_mem_mb) + "m";
     JavaVMInitArgs vm_args;
     auto options = std::make_unique<JavaVMOption[]>(2);
```

The next problem is related to SQLite test database, I don't know yet how to fix it.

**Comment by ienkovich** [comment]
> Due to path differences the tests do not work for HDK
> 
> HDK implementation of `get_root_abs_path` differs because `BUILD_SHARED_LIBS` and `ENABLE_SHARED_LIBS` have different default values for omniscidb and hdk. This can be fixed with the following patch:

Current `get_root_abs_path` implementation for shared libraries targets installed HDK. The difference between installed and not installed cases is that `OSDependent.so` (where `get_root_abs_path` is located) has a deeper build path compared to all other shared libraries. When installed, all libraries are on the same level. So, the proposed fix above will break the installed HDK case. 

The easiest workaround is probably to move `OSDependent.so` upper in the build tree. Here is a possible fix:
```
--- a/OSDependent/Unix/CMakeLists.txt
+++ b/OSDependent/Unix/CMakeLists.txt
@@ -3,5 +3,6 @@ if(BUILD_SHARED_LIBS)
 endif()

 add_library(OSDependent ${OSDEPENDENT_SOURCE_FILES})
+set_target_properties(OSDependent PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/..)

 target_link_libraries(OSDependent Logger)
```
We might also come up with a more comprehensive solution. Probably, use multiple search dirs.

**Comment by leshikus** [comment]
Completed
