### ISSUE TITLE
CI doesn't report broken PyHDK tests

### ISSUE THREAD

**Issue by ienkovich** [intel-ai/hdk#223]
About a month ago `python/tests/test_pyhdk_bindings.py::TestArrowStorage::test_import_arrow_table` test was broken and CI didn't report it.

**Comment by ienkovich** [comment]
Looks like the problem is in `.github/workflows/modin.yml` where we run `python` for our test files instead of `pytest`.

**Comment by alexbaden** [comment]
I don't think that modin test is doing what we think -- the goal is to run modin tests on pyhdk, not pyhdk tests with modin installed. 

I added a new job here: https://github.com/intel-ai/hdk/actions/runs/4298695189/jobs/74931060507 which just runs pytest without modin. It's failing on main, which is the result we currently expect.
