### ISSUE TITLE
Query execution fails because the query contains not supported self-join pattern.

### ISSUE THREAD

**Issue by AndreyPavlenko** [intel-ai/hdk#255]
The following modin code:
```python
import modin.pandas as pd
df = pd.DataFrame({"a": [1]})
print(pd.merge(df, df))
```
fails with error:
```
Query execution fails because the query contains not supported self-join pattern. We suspect the query requires multiple left-deep join tree due to the join condition of the self-join and is not supported for now. Please consider rewriting table order in FROM clause.
```

**Comment by ienkovich** [comment]
Confirm the problem. I'll investigate if we can support this case in a reasonable time or modify the code generated by modin to make it work.

**Comment by AndreyPavlenko** [comment]
Submitted PR to Modin - https://github.com/modin-project/modin/pull/5892

**Comment by Garra1980** [comment]
> Submitted PR to Modin - [modin-project/modin#5892](https://github.com/modin-project/modin/pull/5892)

it is merged, can we close this now?

**Comment by AndreyPavlenko** [comment]
The issue has been fixed for this simple example, but the error is still reproducible on a more complex workflow. Unfortunately, I don't have a simple reproducer, but, if required, I can share the query json.
