### ISSUE TITLE
RuntimeError: ERR_DIV_BY_ZERO is thrown on MOD operation

### ISSUE THREAD

**Issue by AndreyPavlenko** [intel-ai/hdk#271]
However, division operation works properly, but there are inconsistencies with Pandas:

```python
import pandas
import modin.pandas as pd

df1 = pandas.Series([1])
df2 = pandas.Series([0])
print(df1 / df2)  # -> inf
print(df1 % df2)  # -> NaN
print(df1 / 0)  # -> inf
print(df1 % 0)  # -> NaN
print(df2 / 0)  # -> NaN
print(df2 % 0)  # -> NaN

df1 = pd.Series([1])
df2 = pd.Series([0])
print(df1 / df2)  # -> inf
print(df1 % df2)  # -> NaN
print(df1 / 0)  # -> NaN
print(df1 % 0)  # -> RuntimeError: ERR_DIV_BY_ZERO
print(df2 / 0)  # -> NaN
print(df2 % 0)  # -> RuntimeError: ERR_DIV_BY_ZERO
```

**Comment by alexbaden** [comment]
There is a config flag `null_div_by_zero` which by default is `false`. We can try setting it to true by default. @ienkovich is this exposed in pyhdk currently?

**Comment by ienkovich** [comment]
When we execute `df1 / df2` and `df1 % df2` it actually defaults to Pandas and that's why we have the correct answer. When we execute `df1 / 0` we get NaN because `null_div_by_zero` is set to 1. If we want to get `inf` and `-inf`, then we simply should use `inf_div_by_zero` instead. BTW this flag works for FP division only.

I think I'll add `null_mod_by_zero` flag to cover the MOD case here.

**Comment by ienkovich** [comment]
@AndreyPavlenko Required changes have been merged into HDK main branch. Could you please check everything works as expected? In my local runs, it worked. You should set `inf_div_by_zero` in Modin instead of `null_div_by_zero` and add `null_mod_by_zero` option to get desired HDK behavior.

**Comment by AndreyPavlenko** [comment]
@ienkovich thanks. it works. I've created a modin issue https://github.com/modin-project/modin/issues/5812. When the next version of HDK is released, I'll submit a modin PR.

**Comment by ienkovich** [comment]
@AndreyPavlenko Should we add some version info into PyHDK so that we could utilize new features in Modin keeping it compatible with older PyHDK versions?

**Comment by AndreyPavlenko** [comment]
IMHO it's not currently required, because the Modin's HDK backed has a strict version dependency on pyhdk, but the version info could be useful anyway.

**Comment by ienkovich** [comment]
Closing it since the rest of the solution is going to be in Modin.
