### ISSUE TITLE
ArrowPeriodType is not yet supported

### ISSUE THREAD

**Issue by AndreyPavlenko** [intel-ai/hdk#291]
Code to reproduce:

```python
import modin.pandas as pd

df = pd.DataFrame(
    {
        "period": pd.period_range("2023-01", periods=3, freq="M"),
    }
)
print(df.dropna())
```
Output:
```
"_storage.pyx", line 284, in pyhdk._storage.ArrowStorage.importArrowTable
RuntimeError: extension<pandas.period<ArrowPeriodType>> is not yet supported. id: extension
```

**Comment by alexbaden** [comment]
How important is supporting this data type in the context of workloads we are targeting for performance improvement?

**Comment by AndreyPavlenko** [comment]
Zero importance in the context of workloads, afaik. I stumbled upon this problem when running the modin unit tests.

**Comment by alexbaden** [comment]
Thx! Will prioritize accordingly.

**Comment by ienkovich** [comment]
There are many types we don't currently support. Shouldn't we default to pandas for this one?

**Comment by AndreyPavlenko** [comment]
Created Modin PR - https://github.com/modin-project/modin/pull/5987
