### ISSUE TITLE
Intel ARC code generation fails when double type is present in the IR

### ISSUE THREAD

**Issue by kurapov-peter** [intel-ai/hdk#322]
L0Mgr fails to build the module with double type involved on Intel ARC as it doesn't support it.
Build log error:
```
error: Double type is not supported on this platform.
```
The executor then fails with:
```
2023-03-24T07:50:18.065923 F 5885 0 0 Execute.cpp:3202 Check failed: gpu_generated_code
```

**Comment by ienkovich** [comment]
Do we have to avoid double type when using GPU? We use double type as the default result type for some operations (e.g. trueDiv, avg).

**Comment by kurapov-peter** [comment]
Only for certain GPU models. We should have a single place to handle all the unsupported operations, I agree.
