### ISSUE TITLE
Add TSAN, ASAN, UBSAN to CI

### ISSUE THREAD

**Issue by alexbaden** [intel-ai/hdk#35]
Blocked by #34

**Comment by Garra1980** [comment]
@leshikus  could you please provide status where we are now

**Comment by alexbaden** [comment]
We discussed this and there are likely development issues w/ getting the sanitizers running. I have always had more success with clang then gcc when running sanitizers, so I asked Alexei to look into https://github.com/intel-ai/hdk/issues/418.

**Comment by leshikus** [comment]
Done
