### ISSUE TITLE
SIGSEGV on importing arrow table with null columns

### ISSUE THREAD

**Issue by AndreyPavlenko** [intel-ai/hdk#393]
Code to reproduce:
```python
import modin.pandas as pd
df = pd.DataFrame(columns=["a"])
print(df + df)
```
Output:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f65ab0f32f5, pid=273311, tid=273311
#
# JRE version: OpenJDK Runtime Environment (17.0.3) (build 17.0.3-internal+0-adhoc..src)
# Java VM: OpenJDK 64-Bit Server VM (17.0.3-internal+0-adhoc..src, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libArrowStorage.so+0x2a2f5]  ArrowStorage::computeStats(std::shared_ptr<arrow::ChunkedArray>, hdk::ir::Type const*, ChunkStats&)+0x85
```
The error occurs when importing an arrow table with null columns:
```python
import pyarrow as pa
from modin.experimental.core.execution.native.implementations.hdk_on_native.hdk_worker import (
    HdkWorker,
)
table = pa.table([[]], schema=pa.schema([pa.field("A", pa.null())]))
HdkWorker().import_arrow_table(table, "test")
```
I'm not sure if adding support for null columns is required, but, anyway, it shouldn't crash and an exception should be thrown instead.

**Comment by ienkovich** [comment]
@Devjiu You have recently added the support for an empty column import. Please check what's going on for this test case.

**Comment by Devjiu** [comment]
I am sorry, I am not sure it's a bug. 

In this example we are creating null schema. It's column, where can be only nulls. 
During previous issue this case was decided to not support. 

Do we need it?

**Comment by ienkovich** [comment]
How is it different from the case when we parse CSV where one of the columns has NULLs only? IIRC we decided to use float type for such columns. Anyway, SEGFAULT on import is a bug. If we deliberately refuse to import some data, there should be an exception with an explanation.

**Comment by Devjiu** [comment]
On reproducing original code, get an modin error, wrote about it here: https://github.com/intel-ai/hdk/pull/446#issuecomment-1531345103.
