### ISSUE TITLE
Modin doesn't work with PyHDK with submodule updated to the latest jit-engine branch

### ISSUE THREAD

**Issue by ienkovich** [intel-ai/hdk#45]
If I update omniscidb submodule to the latest jit-engine branch then I get this error trying to parse RelAlg JSON queries in Calcite:
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonIncludeProperties
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findPropertyInclusionByName(JacksonAnnotationIntrospector.java:321) ~[calcite-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
```
Looks like it is related to the latest change in the `jackson-databind` version used by Calcite. The problem can be reproduced using `ienkovich/config` of HDK and `ienkovich/pyhdk-config` branch of Modin.

**Comment by alexbaden** [comment]
@vlad-penkin can we fix this separately from the other conda work we want to land? Additional changes to hdk are required to make the HEAD of `jit-engine` work, and it will only get more complicated as we get further behind.

**Comment by Garra1980** [comment]
@vlad-penkin intel-ai/omniscidb#445 should fix the problem
