### ISSUE TITLE
Support python 3.11 in conda-forge

### ISSUE THREAD

**Issue by alexbaden** [intel-ai/hdk#452]
We should allow `pyhdk` to be installed into conda-forge environment using python 3.11.

**Comment by alexbaden** [comment]
Let's do a new 0.5 build. Does it need a new version or just a new build?

**Comment by leshikus** [comment]
should I update the source for the new build? if yes, the release version should be >= 0.6.0

**Comment by Garra1980** [comment]
Just a new build

**Comment by alexbaden** [comment]
Done w/ https://github.com/conda-forge/hdk-feedstock/pull/23
