### ISSUE TITLE
COUNT aggregation fails if the number of groups > 44_739_242

### ISSUE THREAD

**Issue by AndreyPavlenko** [intel-ai/hdk#695]
The following code:

```python
import modin.pandas as pd

df = pd.DataFrame({"a": range(44_739_242 + 1)})
print(df["a"].value_counts())
```
Fails with error:
```
[info]    0 0 RelAlgExecutor.cpp:699 Check failed: agg
```
However, it does not fail if the range is <= 44_739_242 .

**Comment by ienkovich** [comment]
This problem is caused by two subsequent sort nodes. I'll fix the bug, but you should check a tree generated by Modin. There is no use in making two sorts in a row because it's not guaranteed to be stable and therefore only the last one would matter.
