### ISSUE TITLE
Support extract/date time runtime in L0 backend

### ISSUE THREAD

**Issue by alexbaden** [intel-ai/hdk#86]
For Taxi Q3/Q4, we need to determine how to pull the Date/Time runtime into SPIRV. For CUDA, we compile the extension functions into a CUDA FatBinary at build time, then use the CUDA linker. We could follow a similar approach with SPIRV, or move the time extraction functions to the module and inline them during the JIT process. The downside to this could be increased module compile time (though there are some optimizations meant to keep such increases to a minimum), so we are considering building a benchmark to test.

**Comment by kurapov-peter** [comment]
Date/Time runtime is now part of the main runtime module (https://github.com/intel-ai/omniscidb/pull/569). For CUDA they are removed from the FatBinary so that the flow is identical for all the devices. On the CPU side some redundancy exists, see the PR for details.
